{% set name = "flake8-rst-docstrings" %}
{% set version = "0.1.2" %}
{% set sha256 = "7d34d2175a0cd92aba0872ade74268b2f2c12582c7267d4a0e6ef1c32a828ce3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.3
    - pip
  run:
    - python >=3.3
    - flake8 >=3
    - restructuredtext_lint
    - pydocstyle >=3.0.0
    - pygments

test:
  commands:
    - 'flake8 --version | grep rst-docstrings:'

about:
  home: https://github.com/peterjc/flake8-rst-docstrings
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: Extension for flake8 for validating Python docstrings as reStructuredText
  dev_url: https://github.com/peterjc/flake8-rst-docstrings
  description: |
    This is a flake8 plugin for validating Python docstrings markup as reStructuredText
    (RST) using the Python library docutils, called via Todd Wolfson's package
    restructuredtext-lint.

extra:
  recipe-maintainers:
    - peterjc
