travis:
  secure:
    BINSTAR_TOKEN: gyDs1j4G4UxAYoLf3+qBpJG6UEfRd7o5zVbk9Ql4zshY90iNjOX6rSyXnFMSrNQjm/Xmhj9xnA9H8eAMYBQp02rEzHddUfcq5I23FHwar79K1B5dJ2OapqjP//Ku0ze0QxWFl00BKGh9zHAQkKjbeoWVJlm20GtEvpM6Tl9tJ38iLweG13GBWn9x4qlMBEMmKKcVz9JQ3jpyW3JNMAriVBn6IYybPxZ/vKGhjotiMzVaxL1xexJc9gc7eiATMnQLDu/apl2C95PX2CMV/WaBcQOj6LCFU2/vLg4yArtQv1OgRWJfQbW/DnEXw/ggSv1sm3f+mWlPHSdLn8iHGPjewm5LBz0jHsW1rp4ECCvCcVGUKxpUD/JvN/zvIgv4zpct5uXc2yEzhSX8tdhmxMWZowvNIL5urm863QZdVr2IlUuqR1U33pW88w43ZxmFTxdckmlRnOI0wrarkH6e9vBSqpBaMUAftHHvuO0WLgn9Z3nTR6bDL+Yc/Ig29UVu5dJY0VznApPpT5jJYJBh3XGXz2xEkl7WRU5o5BTLYHlErjATt2Jkaf+Yjn42ug//2nm7cSE5sSk7hJMZae54MJ3Bs3YHUbb04Nbn8m+OWY5HB1EwoeGwD9oe13x+UagBKU/B52leQDFaYmDtlqh3HmG7kM71piSqRSat40Newb1zPhM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
